/*
 * This source file was generated by the Gradle 'init' task
 */
package net.minescript.interpreter;


public class Main {
  public static void main(String[] args) {
    System.out.println("Hello, world!");
  }
}
