/*
 * This source file was generated by the Gradle 'init' task
 */
package net.minescript.interpreter;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    @Test public void appHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
